### ISSUE TITLE
any chance to give a game like demo?

### ISSUE THREAD

**Issue by xukongwen** [andrew-wilkes/godot-behaviour-tree#1]
great one! but can you give us a game like demo? so we can learn more?
thanks!

**Comment by andrew-wilkes** [comment]
Hi thanks! Yes, it is a good idea to provide a game-like demo. I have never used a behaviour tree in a game yet though. But I should try it out in a game. Now I am starting a new game development that could have a use for it for control of npc objects.

**Comment by xukongwen** [comment]
good luck for your new game, waiting the demo, thank you.
